// <auto-generated /> 03/13/2014 14:16:55

using Entities;

namespace Factories
{
	public partial class EntityFactory
	{
		public Entity Create(IValueProvider valueProvider)
		{
			var result = new Entity();
			BeforeBuild(result, valueProvider);

			result.Id = valueProvider.GetValue<System.Int32>("ID");
			result.Name = valueProvider.GetValue<System.String>("GroupName");
					
			AfterBuild(result, valueProvider);
			return result;
		}

		partial void AfterBuild(Entity value, IValueProvider valueProvider);
		partial void BeforeBuild(Entity value, IValueProvider valueProvider);
	}

	public partial class Entity2Factory
	{
		public Entity2 Create(IValueProvider valueProvider)
		{
			var result = new Entity2();
			BeforeBuild(result, valueProvider);

			result.GroupId = valueProvider.GetValue<System.Int32>("GroupId");
			result.Unknown = valueProvider.GetValue<System.String>("Unknown");
					
			AfterBuild(result, valueProvider);
			return result;
		}

		partial void AfterBuild(Entity2 value, IValueProvider valueProvider);
		partial void BeforeBuild(Entity2 value, IValueProvider valueProvider);
	}

}

