// <auto-generated />
namespace SqLiteEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Initials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initials));
        
        string IMigrationMetadata.Id
        {
            get { return "201404010912180_Initials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
